### ISSUE TITLE
LDAP Bind needed to complete the connection

### ISSUE THREAD

**Issue by kichetof** [wiltonsr/ldapAuth#1]
Hello,

Thanks for your great plugin!
Unfortunately, I can't use it because my AD doesn't support anonymous connection.

As you can see in the log, authentication failed because no bind was performed _(LdapErr: DSID-0C090A71)._

```
time="2022-01-06T13:02:04+01:00" level=error msg="2022/01/06 13:02:04 Filter => (sAMAccountname=kichetof)" plugin=plugin-ldapAuth module=github.com/wiltonsr/ldapAuth
time="2022-01-06T13:02:04+01:00" level=error msg="2022/01/06 13:02:04 Attributes => [sAMAccountname]" module=github.com/wiltonsr/ldapAuth plugin=plugin-ldapAuth
time="2022-01-06T13:02:04+01:00" level=error msg="2022/01/06 13:02:04 &{[] [] []}" module=github.com/wiltonsr/ldapAuth plugin=plugin-ldapAuth
time="2022-01-06T13:02:04+01:00" level=error msg="2022/01/06 13:02:04 LDAP Result Code 1 \"Operations Error\": 000004DC: LdapErr: DSID-0C090A71, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v3839\x00" plugin=plugin-ldapAuth module=github.com/wiltonsr/ldapAuth
time="2022-01-06T13:02:04+01:00" level=error msg="2022/01/06 13:02:04 Search failed" plugin=plugin-ldapAuth module=github.com/wiltonsr/ldapAuth
time="2022-01-06T13:02:04+01:00" level=error msg="2022/01/06 13:02:04 Authentication failed" plugin=plugin-ldapAuth module=github.com/wiltonsr/ldapAuth
```

My middleware configuration:

```toml
[http.middlewares]
  [http.middlewares.admin-auth.plugin.ldapAuth]
    enabled = "true"
    host = "ldap://x.x.x.x"
    debug = "true"
    port = "389"
    baseDn = "OU=Admin,DC=foo,DC=bar,DC=co"
    userUniqueId = "sAMAccountname"
```

In the [`go-ldap` library](https://github.com/wiltonsr/ldapAuth/blob/master/vendor/github.com/go-ldap/ldap/v3/bind.go), they're the possibility to perform a [bind](https://github.com/wiltonsr/ldapAuth/blob/master/vendor/github.com/go-ldap/ldap/v3/bind.go#L98) to the server.

What do you think about added it to the plugin? _(I've no knowledge in Go to create a PR 😅)_

Many thanks for your help!
Tof

**Comment by wiltonsr** [comment]
Hi @kichetof, thanks for using this project.

This is already a problem I had mapped out. I'm already working on a new release to make the plugin work closer to the enterprise version of Traefik and this release will already have this problem fixed.

**Comment by kichetof** [comment]
Hi @wiltonsr, thanks for your quick update!
Glad to hear that! I'll be happy to implement it when it'll ready! :)

**Comment by wiltonsr** [comment]
Hi @kichetof,

I finished the adjustments. Please test and let me know if there were any problems.

Please be aware of the changes that have occurred in the plugin parameters. You can check them [here](https://github.com/wiltonsr/ldapAuth#options).

**Comment by kichetof** [comment]
Hi @wiltonsr,
Many thanks for this update!
Login works very well! Thanks! 😎

Now, I'm looking to solve the username forwarding that seems not working:

```toml
[http.middlewares]
  [http.middlewares.admin-auth.plugin.ldapAuth]
    enabled = "true"
    url = "ldap://x.x.x."
    debug = "true"
    port = "389"
    baseDn = "OU=Users,DC=domain,DC=com"
    userUniqueID = "sAMAccountname"
    bindDN = "user"
    bindPassword = "pass"
    forwardUsername = "true"
    forwardUsernameHeader = "Username" # already tried sAMAccountname instead
    forwardAuthorization = "true"
```

And the access log _(--> without username for LdapAuth)_:

```
BasicAuth
x.x.x.x - kichetof [07/Jan/2022:08:44:53 +0100] "GET /dashboard/ HTTP/2.0" 200 3124 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" 41 "dashboard@file" "-" 6ms

LdapAuth
x.x.x.x - - [07/Jan/2022:10:20:07 +0100] "GET /dashboard/ HTTP/2.0" 200 3124 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" 284 "dashboard-ldap@file" "-" 23ms
```
