### ISSUE TITLE
Does plugin have some form for auth

### ISSUE THREAD

**Issue by mfominov** [wiltonsr/ldapAuth#11]
Does plugin have some for for auth?

Or maybe we can configure basic auth to pass data to plugin?

**Comment by wiltonsr** [comment]
Hi, 

This plugin is exclusive to `LDAP Auth`.

For `basicAuth`, you could use [official Traefik plugin](https://doc.traefik.io/traefik/v2.0/middlewares/basicauth/).

**Comment by mfominov** [comment]
Does it have some form for authentication?

**Comment by wiltonsr** [comment]
Yes, it uses de default `user` and `password` form from [`basicAuth`](https://github.com/wiltonsr/ldapAuth/blob/5422bd3125730812c1a7316b363e3017dc091554/ldapauth.go#L104), but uses this data to bind to an `LDAP` Server.

**Comment by mfominov** [comment]
This is my ldap middleware configuration for ldap
```
    ldap-auth:
      plugin:
        ldapAuth:
          searchFilter: (&(objectClass=inetOrgPerson)(uid=%s))
          Attribute: uid
          BaseDn: dc=os,dc=novalocal
          Enabled: "true"
          Host: ldap://ldap-server
          bindDN: uid=traefik,cn=users,cn=accounts,dc=gostech,dc=novalocal
          bindPassword: password
          LogLevel: DEBUG
          Port: "389"
          ```

**Comment by wiltonsr** [comment]
Check [examples](https://github.com/wiltonsr/ldapAuth/tree/master/examples) and test with `curl`.

**Comment by mfominov** [comment]
I've only see this on page
401 Unauthorized
Error: [no valid 'Authentication: Basic xxxx' header found in request]

**Comment by mfominov** [comment]
Some strange error
LDAP Result Code 200 "Network Error": parse ":389": missing protocol scheme

**Comment by mfominov** [comment]
Ok. curl works fine.
But i don't see any form to pass credentials.
Maybe i need add something more?

**Comment by wiltonsr** [comment]
Try again in an incognito tab.

**Comment by mfominov** [comment]
I've in another browser
<img width="586" alt="image" src="https://user-images.githubusercontent.com/8983289/159273410-39854a92-5125-49c3-afac-0f529fe72256.png">

**Comment by wiltonsr** [comment]
Try access `http://logout:logout@your-url.com` to see if works.

Otherwise, try to run an example.

**Comment by mfominov** [comment]
Found the answer.
on start i see this
```
...
traefik[14295]: DEBUG: ldapAuth: 2022/03/21 17:11:36 restricted.go:51: WWWAuthenticateHeader => 'false'
```
then i passed 
```
wwwAuthenticateHeader: true
```
and see the basic auth form

https://github.com/wiltonsr/ldapAuth/blob/bde264ed5ec5b7cbdd4440aee71d4ab888df2bba/ldapauth.go#L187-L188

**Comment by wiltonsr** [comment]
Glad to know that works.

[`wwwAuthenticateHeader`](https://github.com/wiltonsr/ldapAuth#wwwauthenticateheader) is `true` by default.

So, unless you explicitly set it to `false` this problem shouldn't happen.

**Comment by mfominov** [comment]
I've not pass false in wwwAuthenticateHeader.
I've even don't have it in my config.

**Comment by mfominov** [comment]
yeap latest
```
experimental:
  plugins:
    ldapAuth:
      moduleName: "github.com/wiltonsr/ldapAuth"
      version: "v0.0.13"
```
