### ISSUE TITLE
Integrity check failed

### ISSUE THREAD

**Issue by dorianim** [wiltonsr/ldapAuth#8]
Hi,

I wanted to try this plugin, but I get this error:
`traefik error: failed to check archive integrity of the plugin github.com/wiltonsr/ldapAuth: plugin integrity check failed`

My config looks like this:
```yml
pilot:
        token: "<my_token>"
experimental:
        plugins:
                ldapAuth:
                        moduleName: "github.com/wiltonsr/ldapAuth"
                        version: "v0.0.9"
```

What am I doing wrong?

Regards,
Dorian
