### ISSUE TITLE
I can't define 'searchFilter' using the File provider

### ISSUE THREAD

**Issue by c0rzair1** [wiltonsr/ldapAuth#9]
I can't define **searchFilter** in _dynamic configuration_ when using the _File provider_.
When I set the config like:

```
http:
  routers:   ...
  services:  ...

  middlewares:
    my-ldapAuth:
      plugin:
        ldapAuthPlugin:
          Enabled: true
          LogLevel: DEBUG
          Url: ldap://someserver
          Port: 389
          BaseDN: DC=com
          BindDN: CN=ldapuser,OU=HUB,DC=com
          BindPassword: Pa$$w0rd
          Attribute: sAMAccountName
          SearchFilter: (&(objectClass=user)(!(objectClass=computer))({{.Attribute}}={{.Username}}))         
```

Then when I run T**raefik** I get the error:
```
traefik    | time="2022-01-20T10:04:58Z" level=info msg="Starting provider *file.Provider {\"watch\":true,\"filename\":\"/configurations/dynamic.yml\"}"
traefik    | time="2022-01-20T10:04:58Z" level=error msg="Cannot start the provider *file.Provider: template: /configurations/dynamic.yml:45:72: executing \"/configurations/dynamic.yml\" at <.Attribute>: can't evaluate field Attribute in type bool"
```

As a workaround, I specified my filter as the default value of an option **SearchFilter** in the file **`ldapauth.go`**:
```
  ...
// CreateConfig creates the default plugin configuration.
func CreateConfig() *Config {
        return &Config{
                Enabled:        true,
                       ...
                SearchFilter:   "(&(objectClass=user)(!(objectClass=computer))({{.Attribute}}={{.Username}}))",
                       ...
                Username:     "",
        }
}
```
